platform: linux

image_resource:
  type: registry-image
  source:
    repository: python

inputs:
- name: cf-performance-tests-pipeline
- name: results

outputs:
- name: results

run:
  path: cf-performance-tests-pipeline/ci/tasks/generate-coverage-table/task.sh

params:
  GIT_COMMIT_EMAIL:
  GIT_COMMIT_USERNAME:
  GIT_COMMIT_MESSAGE: