platform: linux

image_resource:
  type: registry-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks
    tag: latest

inputs:
  - name: cf-performance-tests-release
  - name: cf-performance-tests-pipeline

outputs:
  - name: cf-performance-tests-release

run:
  path: cf-performance-tests-pipeline/ci/tasks/update-cf-performance-tests/task.sh

params:
  GIT_COMMIT_EMAIL:
  GIT_COMMIT_USERNAME:
